### ISSUE TITLE
githubでの作業における注意点

### ISSUE THREAD

**Issue by ysekky** [KosukeMizufune/gunosy_task#1]
- 1つのissueに対して1つのbranchを対応させて作業する
- masterブランチへ直接のコミットはしない
- commitは作業単位にまとめてわかりやすいコミットメッセージを付ける
- PRには対応するissueを紐付ける
- issueに対する質問はissueに(例えばgithubの使い方の質問はこちらに書いてください)

**Comment by KosukeMizufune** [comment]
関さん
お久しぶりです。Gunosyインターン課題修正中の水船です。

１つのissueに対して１つのbranchを対応させるということに関してですが、これは#2,#3,#4の３つ分のブランチを作るという認識でよろしいでしょうか？（#5は#3とほぼ一緒のため）

**Comment by ysekky** [comment]
そうなりますー。それぞれのissueに対して対応するブランチを作り、それをもとにプルリクエストを作ってくださいー

**Comment by KosukeMizufune** [comment]
ありがとうございます！

**Comment by KosukeMizufune** [comment]
マージしたブランチはもう削除しても大丈夫ですかね？
あとこのissueもcloseしますか？

**Comment by ysekky** [comment]
> マージしたブランチは削除してよいか？　

OKです！

> このissueはcloseしますか？

水船さんの中で、一旦OKと思えばOKです。
（githubに慣れる的な意味合いのissueなので）

**Comment by KosukeMizufune** [comment]
ありがとうございます！
