### ISSUE TITLE
mecab_articleのリファクタ

### ISSUE THREAD

**Issue by ysekky** [KosukeMizufune/gunosy_task#14]
- articleってなんだろうって思うと、普通に文字列なんだよね。body_textとか、documentでいい気がする
    - doctowordだしね。
    - ちなみにwordってなっているのに、returnがtokensなのも細かいけど気になる
- 品詞って英語でcategoryだろうか？
- if文の意味がぱっとみわからないのでコメントあるとよさそぷ
    - https://github.com/KosukeMizufune/gunosy_task/blob/master/mecab_article.py#L16
- ってかこれそもそも使われてる？

**Comment by KosukeMizufune** [comment]
views.pyで使われていますよー

**Comment by ysekky** [comment]
なるほど。train_mecabとmecab_articlesの処理はかなり共通だなと思って気になってました。

**Comment by KosukeMizufune** [comment]
最後の返り値で記事のタグを返すか返さないかとデータベースを呼んでいるかで違うのですが、それならファイル名とか変えた方が良さげor統一したファイルで書くべきですかね？

**Comment by KosukeMizufune** [comment]
あと、train_mecabにも同様のコメントを加えるべきだと思ったのですがそれもこのissue内で解決しますか？

**Comment by ysekky** [comment]
train_mecabがmecab_articles.doctowordを呼び出すようにするとスッキリすると思います。

**Comment by KosukeMizufune** [comment]
おお、めちゃくちゃスッキリしました！
