### ISSUE TITLE
READMEにモデル作成の方法が載ってない？

### ISSUE THREAD

**Issue by ysekky** [KosukeMizufune/gunosy_task#15]
気がしたけどどうだろう。get_train.pyはデータ収集だけっぽい

**Comment by KosukeMizufune** [comment]
モデル作成の方法とはどういうことですか？
get_train.pyは確かにデータ収集だけですが

**Comment by ysekky** [comment]
あ、これ、アプリ起動するたびに都度モデル作るんですね…

https://github.com/KosukeMizufune/gunosy_task/blob/master/articleclass/views.py#L11-L13

**Comment by ysekky** [comment]
これは大丈夫です。closeします。
モデル作成は結構時間かかると思うので、別のスクリプトに切り出して、ファイルにして保存。
そしてviewで読み込むだけにしましょうか。
