### ISSUE TITLE
ナイーブベイズのモデルをファイルとして保存し、アプリから学習済みモデルを読み出せるようにする。

### ISSUE THREAD

**Issue by ysekky** [KosukeMizufune/gunosy_task#16]
https://github.com/KosukeMizufune/gunosy_task/blob/master/articleclass/views.p

このように、毎回アプリの起動のたびにモデル作成をやると大変なので、
モデルのパラメータを保存するようにし、それだけ読み出せるようにする。

**Comment by mathetake** [comment]
こっちもマージしたらクローズしましょう
