### ISSUE TITLE
djangoのコマンドでデータ取得~学習~モデルの保存を出来るようにする

### ISSUE THREAD

**Issue by mathetake** [KosukeMizufune/gunosy_task#23]
https://docs.djangoproject.com/en/1.11/howto/custom-management-commands/

ここを参考に 

`python manage.py get_data`
`python manage.py train_model`

とコマンドラインで打つだけで学習用データの取得 & データの取得が出来るようにしましょう。

#16 に関連して、`train_model` コマンドの中でモデルをどこかに保存できるようにできたら良いですね.

**Comment by mathetake** [comment]
コマンドに変数を渡すことも出来るので
`get_data` コマンドに `while count` の上限数も渡せるようにできたら良さげです

**Comment by KosukeMizufune** [comment]
交差検証によるモデル評価もdjangoのコマンドでできるようにしたほうがいいですかね？

**Comment by mathetake** [comment]
もし大変でなければそのほうが良いかもですね

**Comment by mathetake** [comment]
マージしたらcloseしましょう
