### ISSUE TITLE
データベース周りを全てdjangoのappのmodelを使う

### ISSUE THREAD

**Issue by mathetake** [KosukeMizufune/gunosy_task#25]
現在はpymongoを使って各関数の中で直接mongoをread/writeしに行っている状態だと思います。
gunosyでは基本的にmysqlを使ってますので,まず自分のPCにmysqlをインストールしてmysqlデータベースをローカルに立てましょう。

その上で以下のようにそのmysqlにdjangoのORマッパーを使ってread/writeを行うようにしましょう.

- `settings.py` の中の `database` の設定に自分のmysqlの設定を書く
- djangoのappを作成
　- 今の場合 `articles` とかですかね
- 上のアプリの `models.py` を編集する
　- 記事データを格納するテーブルの定義を書く
- djangoのORマッパーを使ってpymongoで行っていたread/writeの処理を全て書き直す

djangoのappとmodel.py周りの解説は以下のチュートリアルを読めば分かるかと思います。
https://docs.djangoproject.com/ja/1.11/intro/tutorial02/
https://docs.djangoproject.com/ja/1.11/intro/tutorial03/

**Comment by mathetake** [comment]
インターンまで時間もないので大変だったら無理しなくて大丈夫ですよ！

**Comment by KosukeMizufune** [comment]
絶賛暇なので（テスト１個しかないので）大丈夫です！
