### ISSUE TITLE
gitignoreの追加

### ISSUE THREAD

**Issue by ysekky** [KosukeMizufune/gunosy_task#4]
人に見せる時、プロジェクトを動かすときに必要のないファイルはgitignoreでコミットに含まれないようにしましょう。
今回では .ideaや__pycache__などが対象です

**Comment by KosukeMizufune** [comment]
関さん

gitignoreとして扱うファイルやフォルダですが、これはdb.sqlite3やmigration、models.pyのようなdjangoにもともと含まれるようなファイルやフォルダもgitignoreとして扱うのですかね？

**Comment by ysekky** [comment]
- db.sqlite3はSQLiteの中身ですね。ケースに寄りますが、環境固有のデータになることが多いので、ignoreすることが多いです。
- migrationはDBを設計するためのものですね。ケースによりますが変更履歴としても重要なのでコミットすることが多いです。
- models.pyはアプリケーション自体のコードですね。ignoreする必要はないです。動作するのに不要なのであれば削除して、必要になったタイミングでまた作るということでいいのではないかなと。

**Comment by ysekky** [comment]
アプリケーションの中身みると、modelsがないのにmigrationが定義されているけど、これは途中作ってたけど、いまはいらなくなったってことでいいのかな？

**Comment by KosukeMizufune** [comment]
migrationはいらなくなったやつです！
ということはmodels.pyもignoreではなく削除ということになるのですかね？

**Comment by ysekky** [comment]
そうなると思います。基本方針としては以下かなと

- githubにコミットされるものは、コードを確認するために必要なもの
- 動くためには必要だが、コードの確認のために不要なものは、gitignoreでコミットしない
- 動くために不要なものはそもそも削除する

**Comment by KosukeMizufune** [comment]
なるほど、わかりやすいです！
ありがとうございます！
