### ISSUE TITLE
Docstringでコメントを書く

### ISSUE THREAD

**Issue by ysekky** [KosukeMizufune/gunosy_task#8]
pythonでの関数におけるコメントは以下のような感じが推奨されます

```
def func1(a, b):
"""
こんな感じでコメントかくよ

:param a: int
:param b: int 
"""
```

変数の定義はいろいろ流派があって、これはSphinx 形式と呼ばれるやつですね。
あんまりこだわりはないですが、

- ダブルコーテーション3つで定義
- 何をする関数か明示されている
- 変数の意味、型が示されている

が満たされていることを求めます

**Comment by KosukeMizufune** [comment]
コメントと変数の定義の間に１行開けるようにしますか？

**Comment by ysekky** [comment]
そのほうが見やすいかなって思いますー
